### ISSUE TITLE
Official docker hub registry needed

### ISSUE THREAD

**Issue by satyrius** [oysterbooks/halfshell#26]
Could you create an official docker hub repo?

**Comment by rafikk** [comment]
Good idea. Here you go: 

    docker run oyster/halfshell config.json

**Comment by satyrius** [comment]
Thanks! You should note this repo in README.

**Comment by satyrius** [comment]
Tags with version numbers will be helpful too ;-)

**Comment by rafikk** [comment]
Yeah, as of now, it's just `latest`. I tried to create a tagged version for 0.1.1 and 0.1.0, but unfortunately their Dockerfile doesn't successfully build anymore; the gophers/go PPA doesn't update. We're pretty close to a 0.2 release, so I didn't bother with it.
